# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootPass
      - MYSQL_PASSWORD=1234
      - MYSQL_USER=Revinder
      - MYSQL_DATABASE=blog_db
    ports:
      - 3306:3306