version: "3.1"

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=blog_db
    ports:
      - 3306:3306
    networks:
      - spring_net

  spring-backend:
    image: spring-backend:latest
    depends_on:
      - "db"
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=blog_db
    ports:
      - 8080:8080
    networks:
      - spring_net
networks:
  spring_net: